services:
  app:
    entrypoint:
      - sleep
      - infinity
    image: docker/dev-environments-default:stable-1
    init: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /Users/lennon/Documents/GitHub/ngx_module_dev
        target: /ngx_module_dev
